- Formula/grass-70.rb
* Updated url and sha. Bottles eft as they were.
> Update of grass-70 from rc2 to release

- Formula/libght.rb
Accoring to issue #85 libght requires cunit.
> Fixed bug in libght

- Formula/gdal-ecwjp2.rb
This updates the local path for the ECW libs after installation. Tested and working on Homebrew 0.9.5 with latest GDAL installation (1.11.2).
> Update path to ECW lib files, update version

- Formula/gdal-110.rb
> Update gdal-110 sha256

- Formula/libnoise.rb
> Update libnoise sha256

- Formula/filegdb-api.rb
As per https://github.com/Esri/file-geodatabase-api/commit/1c46b56f12f906afdb2e003e55cc5e40945d112b
> filegdb-api: update download URL

- Formula/saga-gis-lts.rb
The url to download the file was wrong at gave an error. I've fixed it with the correct one.
> Wrong download url fixed

- Formula/libkml-dev.rb
here is the change I made to install libkml-dev.  I did this for a machine in another project but I don't own a mac myself to test the changes on a fresh machine.  This should work but you should probably test it, or I can tomorrow.
> update libkml-dev SHA256 to match actual

- Formula/grass7.rb
Upgrade grass7 formula to 7.2.2. Fixes #280
> grass7: Update to 7.2.2

- Formula/gdal2-python.rb
This creates site-packages/gdal2-python.pth.
> gdal2-python: creating gdal2-python.pth.

- Formula/gdal2.rb
compile error json.h not found after update by gdal2
- added json-c dependency
> fix compile issues after Xcode update

- Formula/grass7-lts.rb
Add LTS formula, since we bumped `grass7` to a new minor branch (7.4.x)
> Add Grass 7 LTS formula

- Aliases/ossim@2.3
- Formula/ossim.rb
> Upgrade ossim and add alias

- Formula/liblas-gdal2.rb
We now remove the rpath value from the liblas_c dylib, seems to solve the issue.
We're also using the new laszip formula, instead of vendoring our own version.
This should fully address #374
> Fix grass7 linking issue with liblas.

- Formula/ossim.rb
Also removed build patch which has been upstreamed.
> Update ossim to 2.4.0

- Formula/pdfium.rb
Update to the latest version of Chromium.
> Updated pdfium to 3451.

- Formula/gdal2-grass7.rb
- travis/before_install.sh
I guess this is the third PR to get GDAL up to the latest version. Follows #379 and #384.
> Update gdal2-grass7 to 2.3.0

- Formula/grass7.rb
Attempts to address #267, but hiding the changes behind a build flag.
Also enabled freetype and tcl-tk support.
> Enable Aqua GUI for Grass7

- Formula/liblas-gdal2.rb
Update liblas to compile with cxx11.
Also address some issues with building against GDAL 2.3
Should address #387.
> Liblas cxx11

- Formula/qt5-webkit.rb
- travis/before_install.sh
- travis/install.sh
- travis/script.sh
- travis/skip-formulas.txt
First step at addressing the webkit issues described in #403
> Update webkit to the latest version

- Formula/pyqt5-webkit.rb
- travis/before_install.sh
- travis/install.sh
- travis/script.sh
Part 2 of getting webkit working for #403.
> Upgrade pyqt5-webkit to 5.11

- Formula/qt-4.rb
changed url link and mirror to qt4 source
> Qt4 link change

- Formula/qgis2.rb
brew linkapps is deprecated, so suggesting nice replacement
> better linkapps replacement

- Formula/saga-gis.rb
Should address the issue reported in #417.
> Add pkg-config to build requirements

- Formula/ossim.rb
Including GDAL2 by default.
closes #382
> Add additional file format support to ossim.

- Formula/orfeo6.rb
- Formula/saga-gis-lts.rb
- Formula/saga-gis.rb
Should address the issue reported in #423
> Move OpenCV dependency to homebrew-core version.

- Formula/qgis2.rb
- travis/before_install.sh
> Bundle QGIS2 Python dependencies

- Formula/qgis3.rb
@nickrobison @luisspuerto solution to the problem if `ccache` is previously installed: `/bin/sh: ccache: command not found`
> qgis3: fix ccache

- Formula/libght.rb
> Fixed failing build for libght.

- Formula/qgis3.rb
Solution for the problem reported in #436.
> qgis3: fix Processing/GRASS

- Formula/qgis3.rb
Solution for the problem reported in #468.
> qgis3: fix pyproj sha256

- travis/before_install.sh
- travis/install.sh
- travis/script.sh
- travis/skip-formulas.txt
I think that the special handling of `qt5-webkit` will no longer be necessary @nickrobison
Then I will update the formula.
> qt5-webkit: removed special handling

- Formula/qt5-webkit.rb
Solution for the problem reported in #481 #476 #471
@nickrobison First you must merge #483 to generate through the bottle.
> qt5-webkit: fixed

- Formula/gdal2.rb
First PR to upgrade the GDAL stack to 2.3.2
> Upgrade GDAL to 2.3.2

- Formula/qgis3.rb
Solution for the problem reported in #514
> qgis3: update resources

- Formula/gdal2.rb
Solution for the problem reported in #479 #482
I made some changes, the formula works correctly. You can check it @nickrobison mainly the configuration of the arguments, we should consider this later #469 
Tested in Mojave with:
```
brew install -build-from-source gdal2 --with-complete --with-unsupported --with-armadillo --with-libkml --with-opencl --with-postgresql
```
It was installed correctly.
The formula seems to work well. Several changes apply with respect to #494. @nickrobison if you can, check the formula to consider applying them.
@vincentsarago continuation of the pull #491
> gdal2: suggestion of changes in the formula

- Formula/qgis3.rb
Solution for the problem reported in #520
> qgis3: minor changes

- Formula/gdal2.rb
Solution for the problem reported in #526
> gdal2: add dependencies

- Formula/postgis2.rb
Some changes suggested by `brew audit`
> postgis2: minor changes

- Formula/qgis3.rb
> Upgrade QGIS3 to 3.4.2

- Formula/pgsql-ogr-fdw.rb
It was changed to `postgis2`/`gdal2` and fixed build.
> Upgrade PGSQL-OGR-FDW to 1.0.7

- Formula/pdfium.rb
Current release is chromium/3625
> Update pdfium to latest Chromium version (3625)

- Formula/grass7.rb
Solution for the problem reported in #452.
Dependencies, configurations and corrections are added.
> grass7: other corrections

- Formula/osgqt.rb
Dependence for `qgis3 --with-globe`
> Add OGSQT formula

- Formula/qgis3.rb
Solution for the problem reported in #431.
> qgis3: OTB and R integration

- Formula/qgis3.rb
This commit includes fixes for QGIS 3.4.
> qgis3: upgrade OTB plugin

- Formula/openscenegraph-qt5.rb
Dependence for `qgis3 --with-globe`.
> Add OPENSCENEGRAPH-QT5 formula

- Formula/openscenegraph-qt5.rb
Solution for the problem reported in #565.
> openscenegraph-qt5: update formula

- Formula/osgqt.rb
Dependence for qgis3 `--with-globe`.
> osgqt: used openscenegraph-qt5

- Formula/qgis3.rb
Solution for the problem reported in #520.
> qgis3: message in case there is another version of python

- Formula/gdal2-ecwjp2.rb
- Formula/gdal2-filegdb.rb
- Formula/gdal2-grass7.rb
- Formula/gdal2-mdb.rb
- Formula/gdal2-mongodb.rb
- Formula/gdal2-mrsid.rb
- Formula/gdal2-mysql.rb
- Formula/gdal2-ogdi.rb
- Formula/gdal2-oracle.rb
- Formula/gdal2-pdf.rb
- Formula/gdal2-python.rb
- Formula/gdal2-sosi.rb
> Updated GDAL2 downstream packages.

- Formula/qgis3.rb
`r.mapcalc.simple`: Calculates a new raster map from a simple `r.mapcalc` expression
> qgis3: grass - new raster modules

- Formula/orfeo6.rb
Some dependencies and arguments are added for the use of Python 3.
And a script to initialize the environment for OTB executables.
> orfeo6: some fixes for qgis-otb-plugin

- .circleci/before_install.sh
- .travis.yml
- Formula/osgearth-qt5.rb
In addition, the errors of Circle CI and Travis CI are corrected.
> osgearth-qt5: minor changes

- Formula/qgis3.rb
Solution for the problem reported in #583 and #581.
It changes to `--with-saga` for simplicity:
```
option "with-saga", "Build extra Saga GIS (LTS) for Processing plugin"
deprecated_option "with-saga-gis-lts" => "with-saga"
```
> qgis3: fix --with-r and --with-orfeo

- Formula/qgis-ltr@2.18.rb
According to the suggestions in #466
> Add QGIS-LTR@2.18 formula

- Formula/qgis.rb
According to the suggestions in #466
> Add QGIS formula

- Aliases/qgis-214
- Aliases/qgis2-ltr.rb
- Aliases/qgis2.rb
- Aliases/qgis3.rb
Solution for the problem reported in #605
> Fix aliases

- Formula/whitebox.rb
Whitebox GAT provide a platform for advanced geospatial data analysis with applications in both environmental research and the geomatics industry more broadly.
> Add WHITEBOK formula

- Formula/qgis.rb
Solution for the problem reported in #611.
> qgis: fix R plugin

- .circleci/config.yml
- Formula/shark.rb
- travis/before_install.sh
And updated to its latest version.
> Add SHARK from brewsci/homebrew-science

- Formula/six.rb
> Add SIX formula

- Formula/qgis-res.rb
This formula contains the Python Modules that are used in QGIS.
> Add QGIS-RES formula

- Formula/saga-gis-lts.rb
The dependency has been moved to this repository.
> saga-gis-lts: brewsci/science reference is removed

- Formula/orfeo6.rb
The dependency has been updated and moved to this repository.
> orfeo6: brewsci/science reference is removed

- Formula/qgis.rb
@fjperini THANKS A LOT FOR PUT MY NAME HERE!! 🙇 🙏 
I almost did nothing! @fjperini you did all the work. GREAT WORK! we owe you a couple of beers🍻 !!!
> Correcting my name in the formula

- Formula/grass7.rb
Solution for the problem reported in #706.
> grass7: GRASS_PERL is not used

- .travis.yml
- travis/before_cache.sh
- travis/before_install.sh
- travis/changed_formulas.sh
Please add `[skip ci]` to the commit message when the change doesn't require a 
compilation, such as documentation only changes, to avoid unnecessarily wasting
the project's build resources.
https://docs.travis-ci.com/user/customizing-the-build/#skipping-a-build
> Fix travis

- .github/stale.yml
This is just the config for the estale bot
> This is the config for the stalebot

- Formula/osgeo-grass.rb
Small typo correction in the user-facing installation caveats section
> Fix typo in caveats section

- Formula/osgeo-proj.rb
We want to have more control of the updates and supports.
> Add osgeo-proj.rb

- Formula/osgeo-saga-lts.rb
> Update osgeo-saga-lts.rb [ci skip]

- Formula/osgeo-pgadmin3-lts.rb
> Add osgeo-pgadmin3-lts.rb [ci skip]

- Formula/osgeo-postgresql.rb
Solution for the problem reported in #1098
> osgeo-postgresql.rb: revision for icu4c

- Formula/osgeo-sip.rb
The download link for sip changed slightly. 
Please delete options that are not relevant.
Manually confirmed link works
> Fix download link to sip

- Formula/osgeo-qgis.rb
Solution for the problem reported in #1209
> osgeo-qgis: fix splash

- Formula/osgeo-qt-webkit.rb
Solution for the problem reported in #1213
> Upgrade QT-WEBKIT to 5.13.0

- .circleci/after_script.sh
- .circleci/config.yml
> remove sierra builds

- docs/docs/reporting-issues.md
Fixed typo on line 52
Fixes # (issue)
There is no issue related
Syntax fixing
Please delete options that are not relevant.
There is no break on code, so, no collateral damages at sight
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
**Test Configuration**:
* Hardware:
* Operating System:
> Syntax issue on line 52
