Formula/saga-gis.rb
I've updated the saga-gis formula to the latest version as well as fixed a couple of problems.
1. It seems that saga now bundles its own version of projects.h, so pulling in resource from the proj4 repository was causing the build to fail as it was redefining some functions. So I've removed it.
2. The formula was using some deprecated build options which brew audit caught, I fixed those.
=> Update saga-gis to 2.1.4

README.md
The "wiki" link in the README is pointing at the old legacy Homebrew repo. It's deprecated, and there's no wiki there. This PR points users to the current Homebrew documentation instead. (Doco is maintained inside the Homebrew repo now; there's no wiki.)
=> README: update main Homebrew documentation link

Formula/gdal2.rb
GDAL 2.2.2 has been released: https://trac.osgeo.org/gdal/wiki/Release/2.2.2-News
This includes the fix for OpenJPEG 2.2 and to fix a Jasper build issue, so those patches have been removed.
=> Update GDAL to 2.2.2

Formula/gdal2-python.rb
Updating GDAL2-Python to 2.2.2. Will have all the same problems likely with XCode 9, but I assume the bottles will work correctly.
=> gdal2-python: Update to 2.2.2

Formula/grass7.rb
This PR just makes `travis/before_install.sh` explicitly specify `python**@2**`, which fixes the CI build error I see when I try to change anything else in my fork.  I don't know if this will clear existing PRs' errors or not, but it at least clears up one issue.
=> Fix Travis CI error

travis/before_install.sh
This allows us to upgrade the existing python install to Python3, and then install Python2, that way both can exist at the same time. Taken from a discussion on the hombrew [discourse](https://discourse.brew.sh/t/brew-install-python3-fails/1756/6).
This also includes a superfluous change to the gdal2-python formula, in order to trigger the travis build.
This should hopefully resolve the issues in #308.
=> Modify Python installation order

Formula/taudem.rb
This should address the issue reported in #216, we double quote the CXX flags and that seems to work.
I've opened dtarb/TauDEM#168 to try and get the patch upstreamed.
=> Upgrade Taudem to 5.3.7 and fix failing build.

.travis.yml, Formula/gdal2-ogdi.rb, Formula/gdal2-python.rb, Formula/gdal2-sosi.rb, Formula/gdal2.rb, Formula/grass7.rb, Formula/liblas-gdal2.rb, travis/before_install.sh
Building `gdal2-grass7` is currently failing, because the python pre-requesites aren't getting setup correctly.
I think the issue has to do with:
```
echo "Homebrew setup for changed formula ${f}..."
deps=$(brew deps -1 --include-build ${f})
echo "${f} dependencies: ${deps}"
```
The `-1` flag means that when building `gdal2-grass7`, only `gdal2` and `grass7` are listed as dependencies, so the python setup in `before_install.sh` isn't running correctly. This patch simply removes that limitation and gets all the required dependencies, and then does the python things as necessary.
=> Fix Travis Python dependencies

Formula/gdal2.rb, Formula/hdf4.rb
Addresses the issue brought up in #109. Adds an HDF4 formula and the appropriate backend in GDAL2.
@dschneiderch makes a good point that a lot of data is still in the HDF format and there's currently no support for it in homebrew. The HDF4 formulas were removed from core, science and versions.
=> HDF4 support

Formula/ossim@2.1.rb
`orfeo5` does not build with the latest version of `ossim`. As described [here](https://bugs.orfeo-toolbox.org/view.php?id=1499).
This adds the 2.1 release as a versioned formula, which we can then link against in the relevant formulae.
=> Add ossim@2.1 formula

Formula/gdal2-python.rb
So be able to build python binding for GDAL if GDAL is built with head/trunk
=> Update gdal2-python to support building with GDAL trunk

Formula/pyspatialite.rb, travis/changed_formulas.sh
@3nids This PR modifies the way the `MANUAL_FORMULAE` variable is handled by travis. Right now, if we manually specify bottles to build, it also builds the most recently changed formulae, which could mean a lot of duplicate work.
This set the bash script to just return the manually specified formulae, if there are any.
This also rebuilds pyspatialite because I needed something to test against.
=> If manual formulae are specified, build only those formulae.

Formula/qca-qt4.rb
There was a mismatch because `brew audit` recommended adding the `full_index` query param, which changed the checksums.
=> Fix QCA checksums

Formula/laszip@2.2.rb
First step in resolving #374. Splitting out the vendored `laszip` dependency into its own formula.
=> Add laszip 2.2 formula

.travis.yml, travis/before_deploy.sh, travis/bintray-upload.json
This migrates bottle building to a new bintray repository, since S3 doesn't seem to be working with the new travis pro configuration.
Currently, it's using a repository on my own personal organization, but perhaps we can migrate it to a shared organization at some point?
Any existing bottles will remain in S3, which is fine, and hopefully we can move back there once things are working again.
@3nids Does this seem ok to you?
=> Move new bottle building to Bintray

Formula/qgis2.rb, Formula/saga-gis.rb
LTS is now keg only, and QGIS is updated to find it in the local path.
The latest version of SAGA is now available, but it's also keg only, to avoid causing issues with QGIS.
It seems to me that the most common method for using SAGA is via the QGIS plugins, which only supports the 2.3.x branch. Unfortunately, that branch is not compiling on Xcode 9, so we have to build it on Sierra and use the bottle.
The latest version of SAGA is 6.x, but if you have that version in your path, QGIS will fail to find the LTS version. So we'll keep it keg only for now.
=> Update saga gis handling in QGIS and added latest version.

Formula/gdal2.rb
This requires 2 PRs, the first to update gdal2 to the latest version, and a 2nd to update all the other gdal2 formulae, which need the latest version in order to work correctly.
=> Update gdal2 to 2.3.0

Formula/gdal2-ecwjp2.rb, Formula/gdal2-filegdb.rb, Formula/gdal2-grass7.rb, Formula/gdal2-mdb.rb, Formula/gdal2-mrsid.rb, Formula/gdal2-mysql.rb, Formula/gdal2-ogdi.rb, Formula/gdal2-oracle.rb, Formula/gdal2-pdf.rb, Formula/gdal2-python.rb, Formula/gdal2-sosi.rb, travis/changed_formulas.sh, travis/skip-formulas.txt
The 2nd part of the GDAL update. Finishes up #379.
=> Update gdal2 downstream dependencies to 2.3.0

Formula/mongo-cxx-driver-legacy.rb
First step in addressing #184.
This adds the `mongo-cxx-driver-legacy` formula, which is the only driver gdal supports.
=> Add new formula to support mongodb via the legacy driver.

Formula/mongo-cxx-driver-legacy.rb
GDAL requires a shared library, in order to link. So we should build one.
=> Build shared library for mongo client.

Formula/gdal2-mdb.rb, Formula/gdal2-mongodb.rb
Adds mongodb support to GDAL.
Also means osgeo/gdal#676 is unnecessary.
Also does a little cleanup of the `gdal2-mdb` formula.
=> Add mongoDB plugin for GDAL2

Formula/gdal2.rb
With gdal 2.3.0, there's a bug in the Makefile which is preventing the libraries from being installed correctly. This update applies a temporary patch. Addresses. #397
It also removes the MDB installation, which wasn't working anyways, and is handled by `gdal2-mdb`
=> Fix swig library installation

Formula/gdal2.rb
gdal2 wasn’t building because I had more than one formula with the name hdf4
```
==> Upgrading osgeo/osgeo4mac/gdal2 --with-complete --with-opencl --with-armadillo --with-unsupported --with-l
Error: Formulae found in multiple taps:
* osgeo/osgeo4mac/hdf4
* brewsci/science/hdf4
```
I don't know if this is reason to fix the formula.
=> gdal2 depends on hdf4 fix

Formula/gdal2-ecwjp2.rb, Formula/gdal2-filegdb.rb, Formula/gdal2-grass7.rb, Formula/gdal2-mdb.rb, Formula/gdal2-mongodb.rb, Formula/gdal2-mrsid.rb, Formula/gdal2-mysql.rb, Formula/gdal2-ogdi.rb, Formula/gdal2-oracle.rb, Formula/gdal2-pdf.rb, Formula/gdal2-python.rb, Formula/gdal2-sosi.rb
Second part of updating GDAL. Follows #407
=> Update downstream gdal dependencies to 2.3.1

Formula/qt5-webkit.rb, travis/before_install.sh, travis/install.sh, travis/script.sh
Updates the build requirements to remove the need to build all downstream dependencies with the `--no-sandbox` flag. We still need to manually add the flag when building the bottle, because I couldn't find a way to require the sandbox when building from source is an implicit operation, rather than specified by manual arguments. But I think that'll be sufficient for now.
Also addresses the issues noted in #410. There are still some differences in the symbol tables between the Sierra and High Sierra bottles, but I think all the dependencies should be transitively satisfied, so we'll cross that bridge when we come to it.
=> Fix Webkit sandbox and address missing symbols.

Formula/qgis2-ltr.rb
`brew linkapps` is deprecated, suggesting nice replacement
=> better linkapps replacement

Formula/gdal2.rb
This PR adds `ZSTD` compression to gdal2 (gdal>2.3) formula. 
I tested this locally and the install logs looks great. That's said gdal still throw an error when trying ZSTD compression inside geotiff but that might be a configuration problem on my machine 
logs: 
```
$ cat ~/Library/Logs/Homebrew/gdal2/01.configure | grep "zstd"
--with-zstd=/usr/local
checking for ZSTD_decompressStream in -lzstd... yes
```
```
cat ~/Library/Logs/Homebrew/gdal2/01.configure | grep "ZSTD"
checking for ZSTD_decompressStream in -lzstd... yes
ZSTD support:              yes
```
=> add zstd compression

Formula/qgis3.rb, travis/before_install.sh
This new pull is for to have a version of #413 cleaned.
The new `qgis3` is ready, manual intervention is no longer necessary :tada:
It just finished installing. Everything was installed correctly!
@nickrobison `gdal2-python` was built with `python3.6`, it is necessary to update the bottle to avoid problems with some modules.
Thank you very much to all! @nickrobison @luisspuerto 
I hope you can install it without problems!
=> Add QGIS v3.2.1

Formula/qgis3.rb
Solution for the problem reported in #434.
There was not a reference of `${QT_PLUGINS_DIR}/sqldrivers` in `src/providers/spatialite/CMakeLists.txt
`
Checking I found
```
qsqlspatialite
external/qspatialite/CMakeLists.txt
${QT_PLUGINS_DIR}/sqldrivers
spatialiteprovider
src/providers/spatialite/CMakeLists.txt
${QGIS_PLUGIN_DIR}
```
=> qgis3: fix qspatialite

Formula/gdal2-ecwjp2.rb, Formula/gdal2-filegdb.rb, Formula/gdal2-grass7.rb, Formula/gdal2-mdb.rb, Formula/gdal2-mongodb.rb, Formula/gdal2-mrsid.rb, Formula/gdal2-mysql.rb, Formula/gdal2-ogdi.rb, Formula/gdal2-oracle.rb, Formula/gdal2-pdf.rb, Formula/gdal2-python.rb, Formula/gdal2-sosi.rb
Second part of upgrading GDAL to 2.3.3, follows up #494.
=> Upgrade remainder of the GDAL stack to 2.3.2

Formula/oracle-client-sdk.rb
This PR updates the files names and checksum to be compatible with the Oracle Client SDK packages currently available on [https://www.oracle.com/technetwork/topics/intel-macsoft-096467.html](url)
Issue #486
=> Update Oracle Client SDK version number (file name)

Formula/postgis2.rb
The name of the version is changed so that it does not conflict with `homebrew-core/postgis`.
Several changes were applied.
Updated to the latest version (2.5.1)
=> postgis: change the name of the formula and update to the latest version

Formula/qgis3.rb
Solution for the problem reported in #544.
It is only necessary for `grass7`, and it is already in its formula.
=> qgis3: removed dependence x11

Formula/orfeo6.rb
Solution for the problem reported in #431.
Several changes were applied. 
The plugin will be installed in `qgis3` with `--with-orfeo6`
=> orfeo6: integrate to qgis3

.circleci/before_install.sh, Formula/grass7.rb
Should address the issue reported, again, in #507.
It looks like the `liblas` formula from core was added as a dependency, we actually need to use the `liblas-gdal2` formula, since that one links against the `gdal2` formula that we provide.
=> Fix grass7 compilation when liblas is enabled.

Formula/saga-gis-lts.rb
The `--with-app` flag is added
Requires OpenCV 2 or: `'opencv/cv.h' and 'opencv2/core/version.hpp' file not found`
=> saga-gis-lts: fix SAGA.app and OpenCV

Formula/whitebox-tools.rb
A sample of the program working on `qgis3`.
@nickrobison I am preparing other formulas to incorporate more features to `qgis3`.
@luispuerto If you can, write a list of five other functions that we should support.
For example, I have adapted the WBT and TauDEM plugins to be able to use them in `qgis3`.
List of plugins currently supported in qgis3:
- GRASS
- SAGA
- OTB
- R
- TauDEM
- WBT
-  LiDAR - LAStools (soon)
=> Add WHITEBOKTOOLS formula

Formula/qgis.rb
Is used `qgis-res` to have more Python Modules and save build time after installing this dependency. Also to solve reported problems by not finding some of the required modules.
=> qgis: qgis-res is used

Formula/opencollada.rb
Maybe some dependency of `orfeo6` is in need of this package
```
Installing changed formula orfeo6...
==> Installing orfeo6 from osgeo/osgeo4mac
Error: No available formula with the name "opencollada" (dependency of osgeo/osgeo4mac/orfeo6)
```
https://travis-ci.com/OSGeo/homebrew-osgeo4mac/builds/100554719
=> Add OPENCOLLADA formula

Formula/grass7.rb
Add missing equal sign so `--with-opengl=aqua` is correctly added to args.
=> Update grass7.rb - Fix build with aqua option.

Formula/qgis.rb
Due to a failure in the key the bottles were not upload, they are manually loaded.
https://circleci.com/gh/OSGeo/homebrew-osgeo4mac/2567#artifacts/containers/0
=> qgis: fix upload bottles [ci skip]

Formula/osgeo-saga-lts.rb
SAGA still uses projects.h which is removed i9n PROJ 6.0.0.
SAGA should be updated to support the proj.h API.
https://github.com/OSGeo/proj.4/wiki/proj.h-adoption-status
https://sourceforge.net/p/saga-gis/bugs/271/
=> Update osgeo-saga-lts.rb [ci skip]

Formula/osgeo-gdal.rb
[GDAL 3.1.0](https://github.com/OSGeo/gdal/releases/tag/v3.1.0) is now available. this pr required a few other changes aside from the url.
* `--with-mandir` is no longer supported as a configure option. so I removed what I believe are the relevant code parts.
* `--with-curl` was changed to use the curl-openssl dependency location. but I'm not sure why this was needed.
* `--with-xml2` only accepts`yes/no`. GDAL now uses pkginfo to determine the path for libxml2.
I ran `brew audit --strict osgeo-gdal but it returned a lot of issues that seem out of scope for this PR as they already exist on `master`.
please let me know if you have questions or concerns.
=> Upgrade GDAL to 3.1.0

Formula/mapserver6.rb, Formula/osgeo-gmt.rb, Formula/osgeo-insighttoolkit.rb, Formula/osgeo-insighttoolkit@4.rb, Formula/osgeo-ossim.rb, Formula/osgeo-pcl.rb, Formula/osgeo-vtk.rb, Formula/osgeo-whitebox.rb
As of Brew 2.6, the `depends_on` syntax that was used for `java` is no longer supported. This PR addresses this.
Fixes #1407 
Please delete options that are not relevant.
I have tested installing this from my own fork/tap on Big Sur, Homebrew 2.7.5-56-g33dafa4, 2,6 GHz 6-Core Intel Core i7.
=> fix java dependencies
